name: Validate Algos-Practice Folder (JavaScript)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if README.md exists
        run: |
          if [ ! -f "README.md" ]; then
            echo "README.md is missing. Exiting."
            exit 1
          fi

      - name: Check if LICENSE exists
        run: |
          if [ ! -f "LICENSE" ]; then
            echo "LICENSE file is missing. Exiting."
            exit 1
          fi
