name: Validate Algos-Practice Folder (JavaScript)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if README.md exists
        run: |
          if [ ! -f "README.md" ]; then
            echo "README.md is missing. Exiting."
            exit 1
          fi

      - name: Check if LICENSE exists
        run: |
          if [ ! -f "LICENSE" ]; then
            echo "LICENSE file is missing. Exiting."
            exit 1
          fi

      - name: Check folder structure
        run: |
          required_dirs=("arrays" "linked-lists" "dynamic-programming" "recursion" "sorting")
          for dir in "${required_dirs[@]}"; do
            if [ ! -d "$dir" ]; then
              echo "Directory $dir is missing. Exiting."
              exit 1
            fi
          done
          echo "All required directories are present."

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No package.json found. Skipping npm install."
          fi

      - name: Run ESLint
        run: |
          if [ -f "package.json" ] && [ -d "node_modules" ]; then
            npm run lint || echo "Linting issues found."
          else
            echo "No Node.js dependencies found for linting."
          fi
